neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
loader_version_range=[1,)

mod_id=paynow_neoforge
mod_name=PayNow NeoForge
mod_license=MIT

modrinth_loader=neoforge
modrinth_title=NeoForge
modrinth_upload_task=shadowJar
modrinth_supported_loaders=neoforge
modrinth_supported_game_versions=1.21.1
