name: PayNow
author: PayNow
version: 0.0.5
main: gg.paynow.paynowbukkit.PayNowBukkit

commands:
  paynow:
    description: PayNow command
    usage: /paynow
    permission: paynow.admin
    aliases: [pn]