name: Run Gradle on every push

on:
  push:
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6

      - name: Execute Gradle build
        run: ./gradlew buildEverything

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            paynow-bukkit/build/libs/*.jar
            paynow-bungeecord/build/libs/*.jar
            paynow-velocity/build/libs/*.jar
            paynow-fabric/build/libs/*.jar
            paynow-sponge/build/libs/*.jar